import{a as b,S as w,i}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const L="48875390-cd749f18f58e0c0fd72bc8c02",P="https://pixabay.com/api/",v=40;async function h(o,t=1){try{return(await b.get(P,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:v,page:t}})).data}catch(s){throw console.error("Error fetching images:",s),s}}function m(o){return o.map(({webformatURL:t,largeImageURL:s,tags:l,likes:e,views:r,comments:a,downloads:g})=>`
      <a class="gallery-item" href="${s}">
        <img src="${t}" alt="${l}" loading="lazy" />
        <div class="info">
          <p><b>Likes</b> ${e}</p>
          <p><b>Views</b> ${r}</p>
          <p><b>Comments</b> ${a}</p>
          <p><b>Downloads</b> ${g}</p>
        </div>
      </a>
    `).join("")}const S=document.querySelector("#search-form"),p=document.querySelector(".gallery"),u=document.querySelector(".loader"),n=document.createElement("button");n.id="load-more";n.textContent="Load more";n.style.display="none";document.body.appendChild(n);const y=new w(".gallery a",{captionsData:"alt",captionDelay:250});let d="",c=1,f=0;S.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.target.elements.searchQuery.value.trim(),c=1,!d){i.warning({message:"Please enter a search query!",position:"topRight"});return}p.innerHTML="",u.classList.add("show"),n.style.display="none";try{const{hits:t,totalHits:s}=await h(d,c);if(f=s,t.length===0){i.error({message:"No images found. Try a different search query!",position:"topRight"});return}p.innerHTML=m(t),y.refresh(),f>40&&(n.style.display="block")}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u.classList.remove("show")}});n.addEventListener("click",async()=>{c++,u.classList.add("show");try{const{hits:o}=await h(d,c);p.insertAdjacentHTML("beforeend",m(o)),y.refresh(),E();const t=Math.ceil(f/40);c>=t&&(n.style.display="none",i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u.classList.remove("show")}});function E(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
